#!/usr/bin/env sh

# Download tool

# use specific one 'vX.Y.Z' or just 'latest'
VERSION=v0.5.1
OS="darwin"
ARCH="arm64"

EXECUTABLE_ZIP_URL="https://github.com/wttech/aemc/releases/$VERSION/download/aemc-cli_${OS}_${ARCH}.tar.gz"
EXECUTABLE_DIR="bin/aemc-cli/$VERSION"
EXECUTABLE_ZIP_PATH="$EXECUTABLE_DIR/aemc-cli.tar.gz"
EXECUTABLE_PATH="$EXECUTABLE_DIR/aemc-cli/aemc-cli"

if [ ! -f "$EXECUTABLE_PATH" ]; then
  mkdir -p $EXECUTABLE_DIR
  curl -o "$EXECUTABLE_ZIP_PATH" -OJL "$EXECUTABLE_ZIP_URL"
  # TODO unpack
  #chmod +x "$EXECUTABLE_PATH"
fi

# Declare provisioning API

# shellcheck disable=SC2139
alias aem="./$EXECUTABLE_PATH"

# print provisioning step header
step () {
  DATE=$(date "+%Y-%m-%d %H:%M:%S")
  echo "[$DATE] $@"
}

# check last command
clc () {
  if [ "$?" -ne 0 ]; then
    exit "$?"
  fi
}

# format seconds to more nice format
duration () {
  T=$1
  D=$((T/60/60/24))
  H=$((T/60/60%24))
  M=$((T/60%60))
  S=$((T%60))
  (( $D > 0 )) && printf '%d day(s) ' $D
  (( $H > 0 )) && printf '%d hour(s) ' $H
  (( $M > 0 )) && printf '%d minute(s) ' $M
  (( $D > 0 || $H > 0 || $M > 0 )) && printf 'and '
  printf '%d second(s)\n' $S
}

# Include provisioning script that uses API

COMMAND_DEFAULT="setup"
COMMAND="${1:-$COMMAND_DEFAULT}"
SCRIPT="aem/$COMMAND.sh"

if [ -f "$SCRIPT" ]; then
  export AEM_OUTPUT_FORMAT=${AEM_OUTPUT_FORMAT:-none}
  export AEM_INSTANCE_PROCESSING_MODE=${AEM_INSTANCE_PROCESSING_MODE:-parallel}

  STARTED_TIMESTAMP=$SECONDS
  step "script '$COMMAND' started"

  # shellcheck source=aem/*.sh
  . "$SCRIPT"

  ENDED_TIMESTAMP=$SECONDS
  ELAPSED=$((ENDED_TIMESTAMP - $STARTED_TIMESTAMP))
  step "script '$COMMAND' ended in $(duration $ELAPSED)"
else
  aem "$@"
fi
