version: '3'

env:
  AEM_ENV: '{{.AEM_ENV | default "local"}}'
  AEM_INSTANCE_PROCESSING_MODE: auto
  AEM_OUTPUT_VALUE: NONE
  AEM_JAVA_ENABLED: true

dotenv:
  - '.env'              # VCS-ignored, user-specific
  - '.env.{{.AEM_ENV}}' # VCS-ignored, env-specific
  - '{{.AEM_ENV}}.env'  # VCS-tracked, env-specific

includes:
  cli: ./Taskfile.cli.yml
  aem: ./Taskfile.aem.yml