version: "3"
services:
  dispatcher:
    container_name: dispatcher
    image: acme/aem-ams/dispatcher-publish:latest
    ports:
      - "80:80"
    volumes:
      - ./target/docker/httpd/logs:/etc/httpd/logs
      - ./target/docker/httpd/cache:/var/www/cache
