version: "3"
services:
  dispatcher:
    container_name: dispatcher
    image: acme/aem-ams/dispatcher-publish:latest
    platform: linux/amd64
    ports:
      - "80:80"
    volumes:
      - ./home/docker/httpd/logs:/etc/httpd/logs
      - ./home/docker/httpd/cache:/var/www/cache
