FROM httpd:2.4.55-alpine3.17

RUN apk update && apk add ca-certificates && update-ca-certificates && apk add openssl wget
RUN wget https://download.macromedia.com/dispatcher/download/dispatcher-apache2.4-linux-x86_64-4.3.5.tar.gz


