#!/usr/bin/env sh

AEM_DIR="aem"

. ${AEM_DIR}/api.sh

COMMAND_DEFAULT=${AEMC_COMMAND_DEFAULT:-"setup"}
COMMAND="${1:-${COMMAND_DEFAULT}}"
SCRIPT="${AEM_DIR}/script/${COMMAND}.sh"

if [ -f "$SCRIPT" ]; then
  export AEM_OUTPUT_FORMAT=${AEM_OUTPUT_FORMAT:-none}
  export AEM_INSTANCE_PROCESSING_MODE=${AEM_INSTANCE_PROCESSING_MODE:-parallel}

  STARTED_TIMESTAMP=$(date +%s)
  step "script '${COMMAND}' started"
  step "check progress using command 'tail -f ${AEM_DIR}/home/aem.log'"

  # shellcheck source=${AEM_DIR}/*.sh
  . "${SCRIPT}"

  ENDED_TIMESTAMP=$(date +%s)
  ELAPSED=$((ENDED_TIMESTAMP - STARTED_TIMESTAMP))
  step "script '${COMMAND}' ended in $(duration $ELAPSED)"
else
  aem "$@"
fi
