#!/usr/bin/env sh

VERSION=${AEMC_VERSION:-"0.6.4"}
COMMAND_DEFAULT=${AEMC_COMMAND_DEFAULT:-"setup"}

AEM_DIR="aem"
HOME_DIR="${AEM_DIR}/home"
DOWNLOAD_DIR="${HOME_DIR}/tmp"

. aem/api.sh

OS=$(detectOs)
ARCH=$(detectArch)

# Download tool or use installed

BIN_DOWNLOAD_NAME="aemc-cli"
BIN_DOWNLOAD_URL="https://github.com/wttech/aemc/releases/download/v${VERSION}/${BIN_DOWNLOAD_NAME}_${OS}_${ARCH}.tar.gz"
BIN_ROOT="${DOWNLOAD_DIR}/${BIN_DOWNLOAD_NAME}/${VERSION}"
BIN_ARCHIVE_FILE="${BIN_ROOT}/${BIN_DOWNLOAD_NAME}.tar.gz"
BIN_ARCHIVE_DIR="${BIN_ROOT}/${BIN_DOWNLOAD_NAME}"
BIN_NAME="aem"
BIN_EXEC_FILE="${BIN_ARCHIVE_DIR}/${BIN_NAME}"

if [ "${VERSION}" != "installed" ] && [ ! -f "${BIN_EXEC_FILE}" ]; then
  mkdir -p "${BIN_ARCHIVE_DIR}"
  downloadFile "${BIN_DOWNLOAD_URL}" "${BIN_ARCHIVE_FILE}"
  tar -xf "${BIN_ARCHIVE_FILE}" -C "${BIN_ARCHIVE_DIR}"
  chmod +x "${BIN_EXEC_FILE}"
  # shellcheck disable=SC2139
  alias aem="./${BIN_EXEC_FILE}"
fi

# shellcheck disable=SC2139
alias aem="./${BIN_EXEC_FILE}"

# Include provisioning script that uses API

COMMAND="${1:-${COMMAND_DEFAULT}}"
SCRIPT="aem/script/${COMMAND}.sh"

if [ -f "$SCRIPT" ]; then
  export AEM_OUTPUT_FORMAT=${AEM_OUTPUT_FORMAT:-none}
  export AEM_INSTANCE_PROCESSING_MODE=${AEM_INSTANCE_PROCESSING_MODE:-parallel}

  STARTED_TIMESTAMP=$(date +%s)
  step "script '${COMMAND}' started"
  step "check script progress using command 'tail -f aem/home/aem.log'"

  # shellcheck source=aem/*.sh
  . "${SCRIPT}"

  ENDED_TIMESTAMP=$(date +%s)
  ELAPSED=$((ENDED_TIMESTAMP - STARTED_TIMESTAMP))
  step "script '${COMMAND}' ended in $(duration $ELAPSED)"
else
  aem "$@"
fi
