services:
  dispatcher:
    container_name: dispatcher
    image: adobe/aem-ethos/dispatcher-publish:latest
    ports:
      - "80:80"
    environment:
      - AEM_HOST=host.containers.internal
      - AEM_IP=*.*.*.*
      - AEM_PORT=4503
      - DISP_LOG_LEVEL=Warn
      - REWRITE_LOG_LEVEL=Warn
    volumes:
      # Use project-specific dispatcher config
      - ./src:/mnt/dev/src:ro
      - ./home/sdk/lib:/usr/lib/dispatcher-sdk:ro
      - ./home/sdk/lib/import_sdk_config.sh:/docker_entrypoint.d/zzz-import-sdk-config.sh:ro
      # Enable invalidation by any client
      - ./home/sdk/lib/overwrite_cache_invalidation.sh:/docker_entrypoint.d/zzz-overwrite_cache_invalidation.sh:ro
      # Enable hot reload
      #- ./home/sdk/lib/httpd-reload-monitor:/usr/sbin/httpd-reload-monitor:ro
      #- ./home/sdk/bin/validator-linux-amd64:/usr/sbin/validator:ro
      # Enable previewing logs and caches directly on host
      - ./home/sdk/logs:/var/log/apache2
      - ./home/sdk/cache:/mnt/var/www
    sysctls:
      # Fixes: "Permission denied: AH00072: make_sock: could not bind to address [::]:80"
      # See: https://documentation.suse.com/smart/container/html/rootless-podman/index.html#rootless-podman-configure-port-below-1024
      net.ipv4.ip_unprivileged_port_start: 0
